### ISSUE TITLE
Genes not being returned by autocompleter

### ISSUE THREAD

**Issue by kevinschaper** [alliance-genome/agr#100]
It looks like only diseases and go terms are coming back now.

<img width="573" alt="screen shot 2017-02-16 at 1 28 08 pm" src="https://cloud.githubusercontent.com/assets/4535019/23042049/f6f310f0-f44b-11e6-87b1-6717f34159db.png">

**Comment by oblodgett** [comment]
I think this might be something I introduced in loading all the new gene files. I will look into it and try to figure it out.

**Comment by oblodgett** [comment]
Upon further investigation, running older versions of code against the index produces the same results: Diseases and GO with no Genes. So I am leaning toward it being an index issue and not a code issue.

**Comment by kevinschaper** [comment]
I'll take a look at it, the field names are sort of "in transition" between what they were in the prototype and matching the BGI schema, and mostly duplicated, but that seems like a likely culprit.   I've been wanting to have some tests that run against a fully populated index (even if we just run them manually), so this will give me an excuse to do that too.

**Comment by oblodgett** [comment]
It would be nice to have tests that would basically take an empty index inject a DM and then query for it via the different ways that we query, and check that the fields exist and with the same data that was injected. This way we don't create data dependent tests. Which is an issue we have here at MGI. Tests just start failing and time gets waisted, just to find out someone deleted an Allele or OMIM term etc, and our tests were using it.
