### ISSUE TITLE
Disable unsecured PUT/POST/DELETE api methods

### ISSUE THREAD

**Issue by kevinschaper** [alliance-genome/agr#112]
We gained full CRUD support, but I don't think we actually need it for anything yet, and when we add it, we probably should put some kind of authentication in front of it.

**Comment by oblodgett** [comment]
Would it be better to just change this issue to add authentication to the "modifiable" endpoints rather then disabling them? Also right now there is no code behind PUT/POST/DELETE only GET is implemented so others would fail anyway. We need other issues to do the work for these endpoints.

**Comment by kevinschaper** [comment]
What updates are you thinking will come in via the API?   Is MGI thinking of pushing incremental changes to genes?
