### ISSUE TITLE
Don't redownload already downloaded files.

### ISSUE THREAD

**Issue by oblodgett** [alliance-genome/agr#114]
When downloading files from S3 don't download again files that you already have. Carry this idea also onto extracted files, don't extract already extracted files.

**Comment by cmpich** [comment]
Something is wrong: The indexer is not re-downloading ZFIN_0.3.0_3.tar.gz that is correct, but it should find the newer version on S3: ZFIN_0.3.0_4.tar.gz...

**Comment by christabone** [comment]
The filenames are hard-coded in the scripts. ZFIN's is here:

https://github.com/alliance-genome/agr/blob/5c11ce0b1c8d184b025c8b3d7e13e936ec195fb8/scripts/elastic_search/mods/zfin.py#L25-L29

If you've uploaded a new version, please change the filename and commit. :)
