### ISSUE TITLE
Restructure the indexing process, need input.

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr#128]
The rather large data structure `fetch_save_index` is becoming unwieldy with the addition of the DIOPT data (or, attempted addition, as we currently run out of memory on the development machine).

Is it possible to take a new approach to indexing? I was thinking:

1) Delete the old index
2) Create the new index (mapping.py)
3) Parse the gene data into the data structure.
4) Load the gene data into ES via `bulk_data`
5) Keep a _simple_ dictionary for gene_id -> ES id field to use for future data.
6) Initiate loop below.

Loop until finished:
1) Parse the next class of data and load it into ES using the gene_id -> ES id field dictionary from step 5.
2) Delete the data structure for this class.

Thoughts?

**Comment by oblodgett** [comment]
The sooner we are able to move to a database the sooner we will be able to handle incremental loading / indexing.
