### ISSUE TITLE
Convert RGD to use mine.

### ISSUE THREAD

**Issue by oblodgett** [alliance-genome/agr#134]
Instead of loading RGD go and disease annotations from rat_go.tsv and rat_disease.tsv convert over to using Rat Mine.

**Comment by srengel** [comment]
rat_disease will come from RatMine instead of DAF?

**Comment by oblodgett** [comment]
Yes the rat_go and rat_disease should be coming from their mine. I am working with Jeff to get that setup and the data into AGR.

**Comment by jdepons** [comment]
Why wouldn't you use the disease info from our daf file instead of the mine?

**Comment by oblodgett** [comment]
Yes we could I guess... I know that the other mod's are still trying to get the DAF file going. Maybe I will take a crack at it, I am not familiar with the DAF format but there is always something to learn.

**Comment by sierra-moxon** [comment]
We just discussed in DQMs today, about producing a JSON file for disease.  Please don't take a crack at it quite yet?

**Comment by srengel** [comment]
Olin, all disease associations should come from DAFs.  all GO annotations should come from GAFs.  these are standard file formats that all MODs share.  

downstream JSON's are fine/good, but the primary data should come from those file types (GAF, DAF).

**Comment by sierra-moxon** [comment]
Stacia - I thought we had discussed today, representing the data in a hierarchical way so that issues about two delimiters per field, etc.. could be easier to parse and reconcile.  Did I misunderstand that meeting?

**Comment by srengel** [comment]
not sure, Sierra, are we crossing topics?  all i'm trying to say here is that i was concerned about this new decision to take rat disease associations and GO annotations from ratMine instead of daf and gaf.

**Comment by sierra-moxon** [comment]
yes, lets not take it from the mine.  we have good info from disease group on how to represent this data in AGR now.  we will try to produce a json schema for this.  lets spend tech resources parsing and loading and pulling out the data based on that json representation.  we can wait on changing from a tsv file I hope, until that is done.  then all data will be pulled from json, dictated and shaped by the disease working group.

**Comment by oblodgett** [comment]
From my perspective it doesn't matter where the data comes from, but the file that has been checked into the project is old, and not being updated. So where to go for an always up to date version is my question? Doesn't matter if its a DAF, GAF, Mine, JSON, CSV, TSV, whatever.

**Comment by christabone** [comment]
For the prototype (0.3.0) the decision is to use hard-coded data on the UI side. So no worries about uploading new data for now. We plan to load a JSON-version of the DAF for 0.6.0.

@srengel and @sierra-moxon, please correct me if I'm wrong.

**Comment by srengel** [comment]
which file checked in by whom is old and not being updated?

**Comment by oblodgett** [comment]
This file was added a month ago by the person that wrote the prototype, not sure if that was when the repo was created or not.

agr/scripts/elastic_search/data/rat_disease.tsv
agr/scripts/elastic_search/data/rat_go.tsv

Three mods have provided a query to their minds to get this data (MGI, SGD, ZFIN). RGD has a mine, as does FlyBase, so I made the assumption that there was a query provided like the other three and it had just not got implemented yet, the code to implement a mine query is quite straight forward and then we would have RGD on board with the rest.

But there is no standard (in the code at least) on what data and where it comes from or how to store it, in place, so I guess it doesn't matter. If there is a standard then the code should implement it, and not have multiple. If there isn't a standard then we should create one, and then implement it.

**Comment by christabone** [comment]
Sorry for all the confusion Olin. This was something we discussed extensively a few months back (and more recently before you were involved). 

Those files are remnants from the prototype release in December. The disease data is getting a complete rework (DAF/JSON discussion above) so none of the older data are relevant. The standard won't be implemented in time for 0.3.0.

**Comment by christabone** [comment]
Closing this issue for now, if that's OK with everyone, just to try and organize a bit.
