### ISSUE TITLE
Load human data from RGD file

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr#140]
It appears as if we're only loading in `RGD_0.3_basicGeneInformation.10116.json` but not `RGD_0.3_basicGeneInformation.9606.json`.

**Comment by oblodgett** [comment]
Do they both need to be loaded?

**Comment by sierra-moxon** [comment]
One just needs to go in the human.py file, I think.  They used to be loaded before the remodel as they both just ended in .json.

**Comment by christabone** [comment]
Yes, RGD is providing the human data for at least 0.3.0. I'm just about finished with the code additions. Would you have a minute to review the PR to ensure I'm adding them correctly? Currently testing the code...

**Comment by oblodgett** [comment]
Not sure if you are asking Sierra or me but yes.
