### ISSUE TITLE
mouse/rat hexagons swapped on http://52.39.150.209:5000

### ISSUE THREAD

**Issue by srengel** [alliance-genome/agr#147]
mouse and rat hexagons are swapped on gene pages at http://52.39.150.209:5000.  

that is, rat hexagon showing on mouse gene pages, mouse hexagon showing on rat gene pages.  

can you guys please flip those?

**Comment by oblodgett** [comment]
Just updated the site to the latest dev.

**Comment by paaatrick** [comment]
Mice and rats are too similar. This is an upstream bug caused by nature. 😂
