### ISSUE TITLE
did some searches and now the promises are uncaught

### ISSUE THREAD

**Issue by nathandunn** [alliance-genome/agr#171]
Getting these errors in the console:

```
Uncaught (in promise) timeout
search:1 Uncaught (in promise) timeout
search:1 Uncaught (in promise) timeout
jquery.min.js:4 GET http://search.alliancegenome.org/api/search_autocomplete?q=mod-5 500 (Internal Server Error)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
(anonymous) @ fetchData.js:9
n @ fetchData.js:7
value @ index.js:59
onFocus @ Autosuggest.js:350
r @ ReactErrorUtils.js:26
a @ EventPluginUtils.js:85
u @ EventPluginUtils.js:108
d @ EventPluginHub.js:43
y @ EventPluginHub.js:54
n @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
r @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
i @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
i @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
```

**Comment by paaatrick** [comment]
This request fails:

http://52.39.150.209:5000/api/search?limit=50&offset=0&q=mod-5

**Comment by oblodgett** [comment]
Ill take a look at it.

**Comment by kevinschaper** [comment]
@paaatrick does that fail for you on localhost?  it's working locally for me

**Comment by oblodgett** [comment]
We are rebuilding the index on that server at the moment.

**Comment by paaatrick** [comment]
It works for me on localhost, but I haven't reindexed in a long time. Not sure if that's relevant. Currently reindexing on the dev server sounds blameworthy.

**Comment by nathandunn** [comment]
Ahh, @oblodgett  if you think its due to the rebuilding of the index, you can probably close this.

**Comment by oblodgett** [comment]
Well the index is done and the link still does not work... I am trying to get access to the logs at the moment to figure out what's going on.
