### ISSUE TITLE
RGD entries missing "RGD" prefix

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr#183]
![image](https://cloud.githubusercontent.com/assets/3584662/23280707/4a42103e-f9e8-11e6-89bf-7d339a3589fc.png)

An accidental change from the Human Gene Report fix?

**Comment by sierra-moxon** [comment]
I can do this in the backend.

**Comment by christabone** [comment]
@sierra-moxon The code for generating the prefixes is handled by @paaatrick.

Here's the PR that caused the bug: https://github.com/alliance-genome/agr/pull/170/files

If we start changing the data going into the frontend and try to fix it on the backend we might cause a bit of a mess.

**Comment by christabone** [comment]
It's a new bug, the RGD prefix existed before the change in my last comment.

**Comment by sierra-moxon** [comment]
Yay totally, we discussed this here -- if we change it back, then MGI is messy and human...we agreed here to fix in the backend for now.

**Comment by christabone** [comment]
Oh, my bad. Thanks for clarifying.
