### ISSUE TITLE
Literature link on zebrafish gene pages is broken, other species ok

### ISSUE THREAD

**Issue by kevinschaper** [alliance-genome/agr#209]
turns into a relative link, for some reason:

http://staging.alliancegenome.org/gene/http%3A%2F%2Fzfin.org%2Fcgi-bin%2Fwebdriver%3FMIval%3Daa-showpubs.apg%26OID%3DZDB-GENE-141212-402%26name%3Dsi%3Adkey-99n20.7%26abbrev%3Dsi%3Adkey-99n20.7

Since the link is fine for other species, this might be a problem with the ZFIN BGI json rather than the page?

@cmpich @paaatrick ??

**Comment by christabone** [comment]
See #206 :)

**Comment by kevinschaper** [comment]
haha, I found it on my own, but totally a dupe
