### ISSUE TITLE
The GO annotations used for searching include every AGR species but rat?

### ISSUE THREAD

**Issue by jrsjrs** [alliance-genome/agr#215]
If I search for the GO term "axon" I get results from every species except for rat which makes me assume that the GO annotations used for searching do not include any annotations for rat.  Is that the case?  These are the species facets from the search:
Mus musculus	393
Homo sapiens	222
Danio rerio	136
Drosophila melanogaster	105
Caenorhabditis elegans	78
Saccharomyces cerevisiae	2

* Please assign this issue to yourself if you are going to work on it.

* Please label this issue with Frontend, Backend, etc depending on the nature of the issue.

* Please choose a milestone that this issue will be completed under.

**Comment by sierra-moxon** [comment]
The issue was that the GO annotation file used for rat had RGD ids like RGD:12345, while the gene file had 12345 as the id with the prefix (separate column) as RGD.  I checked in a change for this late Friday, I am not sure it made it into the release.  I will follow up on this.

**Comment by jrsjrs** [comment]
Thanks, Sierra!

**Comment by sierra-moxon** [comment]
Hi again  - we reindexed the site this morning and now rat genes are showing up with GO terms.  Can you confirm my testing and if its ok in your opinion, would you mind closing this issue?  Thanks a bunch, Sierra

**Comment by jrsjrs** [comment]
Checked it and what I saw looked good.  Closing the issue.  Thanks!
