### ISSUE TITLE
geneSynopsisUrls not being displayed

### ISSUE THREAD

**Issue by JoelRichardson** [alliance-genome/agr#218]
Gene synopsis text is being displayed, but gene synopsis URLs are not.
Example: 
http://staging.alliancegenome.org/gene/MGI:109337
Should display this URL:
http://staging.alliancegenome.org/gene/MGI:109337

This gene onl;y has a synopsis URL:
http://staging.alliancegenome.org/gene/MGI:98341

**Comment by paaatrick** [comment]
Done

**Comment by JoelRichardson** [comment]
@paaatrick Thanks. But I'm not seeing the change. ?

**Comment by paaatrick** [comment]
Changes are in, but they haven't been deployed yet.

**Comment by oblodgett** [comment]
We have frozen 0.3.0, from any new updates, as in the things are getting fixed but are not pushed to the staging site.

**Comment by JoelRichardson** [comment]
OK thanks.
