### ISSUE TITLE
Move Data files to S3 in prep for possible repo split.

### ISSUE THREAD

**Issue by oblodgett** [alliance-genome/agr#225]

**Comment by cmpich** [comment]
I am not sure what needs to be done... I would vote for getting the data files from the MODs directly through a URL that could be a web service or a just a resource locator to a pre-created file.

**Comment by oblodgett** [comment]
These files have been moved to the S3 bucket and are now being downloaded from there. This issue was to get the files out of the repo and make sure everything works, nothing more.
