### ISSUE TITLE
Make Indexer not be down while indexing...

### ISSUE THREAD

**Issue by oblodgett** [alliance-genome/agr#228]
While the indexer is running run the documents into a TMP index. Then when done delete the current index and make the TMP index the current index.

**Comment by kevinschaper** [comment]
It can also be done with aliasing, so that there's no copy step, just updating which index the alias points to.  Here's some doc on it - https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html

**Comment by oblodgett** [comment]
Yes... that is what I implemented, checkout the current pull request.
