### ISSUE TITLE
The title of the document head not updated with the route

### ISSUE THREAD

**Issue by LucyHut** [alliance-genome/agr#237]
The title field in the html head tag of each agr page being rendered is hardcoded and does not reflect the current route. Although not a big deal, but this could result in agr pages being penalized by search engines -

**Comment by paaatrick** [comment]
There was a suggestion to check out https://github.com/nfl/react-helmet for this.

**Comment by LucyHut** [comment]
A new react component (components/headMetaTags.js) was created using React-Helmet package. This component is then called when the page is created.
