### ISSUE TITLE
genomeLocations has a null start and end all of the time

### ISSUE THREAD

**Issue by nathandunn** [alliance-genome/agr#245]
@christabone   . . @kevinschaper  suggested you might be the person to ask.

```
"gene_molecular_function": [], 
  "genomeLocations": [
    {
      "assembly": "GRCv10", 
      "chromosome": "13", 
      "end": null, 
      "start": null, 
      "strand": null
    }, 
    {
      "assembly": "GRCv10", 
      "chromosome": "13", 
      "end": null, 
      "start": null, 
      "strand": null
    }, 
```

**Comment by kevinschaper** [comment]
Assuming that it's just a typo in passing those fields along, maybe it's something you'll be able to poke at while you're re-writing.

**Comment by sierra-moxon** [comment]
I'm pretty sure this is a ZFIN data issue -- we may not have provided start/end locations because we have so many of them and no way at AGR to say which is the "most" correct.

**Comment by cmpich** [comment]
Yes, we are leaving start and end position info empty if we don't have a single answer in our database. Should we leave out the genome location all together or is the chromosome info alone helpful on it's own?

**Comment by nathandunn** [comment]
You should include the min and the max for each assembly.   If each assembly has a version or a preferred status, I can use that information to choose the proper assembly.  Currently I use the symbol if the min/max information is not available.

**Comment by nathandunn** [comment]
But it should correspond with whatever @scottcain is loading into the JBrowse instance.  I believe that this is what you have available as GFF3 to download.  How is that determined?

**Comment by sierra-moxon** [comment]
The bug says "all of the time" w/re to null start/end.  Is that true?  In the file, many do have start/end not null.

**Comment by christabone** [comment]
It appears to be a loading bug (checked via Kibana). 

I'll address it with the iterative loading patch (ETA end of week?) if that works for everyone.

**Comment by nathandunn** [comment]
@sierra-moxon   It appears to be on rat and C. elegans as well, so I think that @christabone solution should fix that.   If we have a symbol, we'll have the location data as well (so long as it is exported as a GFF3 file).    

I think its fine to have both assemblies on there.  We just need to know which one is actively being used.   Any thoughts on that?   I think that @scottcain  pulls whatever GFF3 is available, so you can probably have a flag in the genomeLocations that indicates the active assembly.

**Comment by sierra-moxon** [comment]
Both assemblies is great!  We don't have that data available yet.  I think my point was, that if we don't submit locations directly, please don't match on symbol.  Or at least let us discuss that.  If there are no locations for a gene , we should probably just have a jbrowse-less gene (for the moment).

**Comment by nathandunn** [comment]
@sierra-moxon  The way I have it set now, if there is no genomeLocation set it shows a "Genome Location Data Unavailable" warning, so I think we are on the same page.
