### ISSUE TITLE
Packaging python code 

### ISSUE THREAD

**Issue by mgrbyte** [alliance-genome/agr#25]
Currently, the top level python package for this project is `src`.
Is this intended?
Conventionally, the src folder contains one or  more packages,
which are collected together with a `setup.py` at the root of the project.

My proposal is to create the following structure (with `.` being the project root):

```
./setup.py
./src
./src/agr
./src/agr/__init__.py  # This is python package
./src/agr/search.py
./src/agr/server.py
./src/agr/indexing/__init__.py
./src/agr/indexing/index.py
./src/agr/indexing/mapping.py
# etc
```

If there's consensus, am willing to work on this.

**Comment by christabone** [comment]
I believe the organization of the project is "OK" for now (haven't heard otherwise from fellow developers). Please re-open if this needs to be discussed again.
