### ISSUE TITLE
Orthology table doesn't stay within Container div when window resize

### ISSUE THREAD

**Issue by bryon-czoch** [alliance-genome/agr#325]

**Comment by sibyl229** [comment]
Hi @bryon-czoch , I'm not sure what you meant. I'm attaching a screenshot of what I see below. Is what you see different? Could you attach a screenshot and let me know what browser you were using? Thank you.

![screen shot 2017-05-26 at 1 32 56 pm](https://cloud.githubusercontent.com/assets/1753893/26505840/4747a312-4218-11e7-83d5-eb918e95d130.png)

**Comment by bryon-czoch** [comment]
[cid:17861B60-FA73-448A-B113-E3EC562AC4C8@indiana.edu]



On May 26, 2017, at 1:37 PM, Sibyl G <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @bryon-czoch<https://github.com/bryon-czoch> , I'm not sure what you meant. I'm attaching a screenshot of what I see below. Is what you see different? Could you attach a screenshot and let me know what browser you were using? Thank you.

[screen shot 2017-05-26 at 1 32 56 pm]<https://cloud.githubusercontent.com/assets/1753893/26505840/4747a312-4218-11e7-83d5-eb918e95d130.png>

**Comment by bryon-czoch** [comment]
![image](https://cloud.githubusercontent.com/assets/6404721/26591940/3a80978e-452d-11e7-9c72-cb725da0a3bd.png)
