### ISSUE TITLE
allow multiple facet values in aggregations API

### ISSUE THREAD

**Issue by ragingsquirrel3** [alliance-genome/agr#33]
Currently, when the user selects, for example, a species facet value, all the other values are hidden.  The aggregations in the search API should show all the values to be displayed, even if the user has selected one (or +1).

I think this can be done by having the the request for the aggregations (which is separate from the results) only use the parameters `q` and `category`, and the have the results request use all the other parameters.  Multiple parameters for the same value should probably be an OR?

**Comment by christabone** [comment]
Closing old prototype-related issues that are not relevant to 0.3.0+. Please re-open if this is incorrect! Thanks.
