### ISSUE TITLE
Default ordering for list of orthologs to be phylogenetic

### ISSUE THREAD

**Issue by selewis** [alliance-genome/agr#52]
As discussed on the 11/16 call

**Comment by gabinkley** [comment]
It was not clear from the gene pair-wise ortholog file how to interpret the phylogeny. This aspect needs more specifications and will not get done by the Dec 6th meeting, but will be added to the enhancement list for the future.

**Comment by selewis** [comment]
Right, Paul will have to point you at the ordering (without branch lengths is good enough for the simple list, though these will be needed for drawing a tree). Here is (some of) what I have derived from PANTHER as of today. (apologies for not using latin, these are shorter to type) which we should use not because it is necessarily "right", but it would make things consistent (and can be easily changed as needed).
human
chimp
macaque
mouse
rat
cow
pig
horse
cat
dog
opossum
anole
frog
fugu
zebrafish
lancelet
sea squirt
sea urchin
fruitfly
mosquito
water flea
trichoplax
dictyostelium
rice
stiff brome
grape
thale cress (arabidopsis)
soybean
poplar
moss
etc... (smaller and smaller things)

**Comment by khowe** [comment]
For what it's worth, a worm needs to be slipped in there. Not sure where exactly, but definitely before the plants!

http://www.treefam.org/browse#tabview=tab2

**Comment by christabone** [comment]
Closing old prototype-related issues that are not relevant to 0.3.0+. Please re-open if this is incorrect! Thanks.
