### ISSUE TITLE
 image corresponding to the organism

### ISSUE THREAD

**Issue by ragingsquirrel3** [alliance-genome/agr#57]

**Comment by paaatrick** [comment]
I have no idea what this issue means. But it's needed for 0.3?

**Comment by christabone** [comment]
I think it's just having the icon for each species on their respective gene page (already implemented?).

**Comment by paaatrick** [comment]
I might be inclined to agree, except that this issue was opened months before a gene page was being discussed.

**Comment by christabone** [comment]
Sure, should we close it then? 

I spent a few minutes the other day trying to organize our Issues, because they're a bit of a mess. 0.3.0 was slapped onto this issue as I assumed the functionality was already in place and we could close it as soon as you and/or others reviewed it.
