### ISSUE TITLE
Write python basic gene info data validator

### ISSUE THREAD

**Issue by sierra-moxon** [alliance-genome/agr#67]

**Comment by cmungall** [comment]
One thought - if we do this all with swagger, then language bindings in python or any other language can be auto-generated. This will server as a syntactic validation, and can also be used as a higher level API to write additional semantic validation checks.

**Comment by christabone** [comment]
Thanks for the info Chris. I haven't worked with Swagger in the past but I'll take a look at it this week.

For now, I've a simple (~30 line) script which simply reads in a file with JSON data and compares it against our schema. More than happy to switch to a Swagger-based-approach moving forward.
