### ISSUE TITLE
Start investigating basic API distribution layer

### ISSUE THREAD

**Issue by sierra-moxon** [alliance-genome/agr#68]
During the architecture-wg meeting we discussed investigating a basic infrastructure for serving user API requests from AGR.  

For 0.3, we just want to investigate, and possibly produce a simple basic gene information webservice.

**Comment by oblodgett** [comment]
Is this not what /gene/{id} does? I guess I don't understand the intent of this issue?

**Comment by christabone** [comment]
This is correct. We have this functionality via the /gene/ endpoint. Closing for now. API discussion will begin in force for 0.6.0.

**Comment by christabone** [comment]
Please re-open if this is incorrect!
