### ISSUE TITLE
How to refer to species in JBrowse URLs

### ISSUE THREAD

**Issue by scottcain** [alliance-genome/agr#83]
This follows on from https://github.com/alliance-genome/agr_schemas/issues/14

With the changes to the schema, each gene page will "know" the taxon id and location of the feature.  What I'd like to know is this: should I use the taxon id for building JBrowse URLs (which will be somewhat unattractive, but pretty future proof) or should I use the something like species name (eg "C_elegans" or "C%20elegans") or use the human readable name ("worm").  Presumably, the gene page will "know" these things to and so would be available for building the URL (right?)

**Comment by paaatrick** [comment]
I think this has been worked out. The full species name is what the gene page gets for basic gene info, and I believe JBrowse has been updated to use it.
